version: '3.7'

services:
  backend:
    image: registry.gitlab.com/rwf-dev/lstboente/iusr-server/backend:${COMMIT:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    restart: "no"
    ports:
      - "3001:3001"
    env_file:
      - .env
